package config

import (
	"flag"
)

// registerFlags binds all CLI flags to the provided FlagSet and cliConfig. Called from Load before Parse.
func registerFlags(fs *flag.FlagSet, cli *cliConfig) {
	fs.StringVar(&cli.URL, "u", "", "target URL")
	fs.StringVar(&cli.URL, "url", "", "target URL")
	fs.StringVar(&cli.URLList, "list", "", "url list file or csv")
	fs.StringVar(&cli.URLList, "url-list", "", "url list file or csv")
	fs.StringVar(&cli.Dirlist, "d", "default", "wordlist path/url/default/fav/subdomain")
	fs.StringVar(&cli.Dirlist, "dirlist", "default", "wordlist")
	fs.StringVar(&cli.Dirlist, "w", "default", "wordlist")
	fs.StringVar(&cli.Extensions, "e", "", "extensions")
	fs.StringVar(&cli.Extensions, "ext", "", "extensions")
	fs.BoolVar(&cli.UseDefaultExtensions, "ext-defaults", false, "use default extension set")
	fs.StringVar(&cli.InputMode, "mode", "clusterbomb", "input mode")
	fs.StringVar(&cli.InputMode, "input-mode", "clusterbomb", "input mode")
	fs.BoolVar(&cli.IgnoreWordlistComments, "ic", false, "ignore wordlist comments")
	fs.BoolVar(&cli.AutoWildcard, "awc", false, "auto wildcard baseline filter")
	fs.BoolVar(&cli.AutoWildcard, "auto-wildcard", false, "auto wildcard baseline filter")
	fs.IntVar(&cli.MaxResponseSize, "max-size", 0, "max response body size in bytes (0 = default 10 MiB cap)")
	fs.IntVar(&cli.MinResponseSize, "min-size", 0, "min response size (bytes)")
	fs.StringVar(&cli.SaveConfigPath, "save-config", "", "save config to file")
	fs.IntVar(&cli.Concurrency, "c", 40, "concurrency")
	fs.IntVar(&cli.Concurrency, "concurrency", 40, "concurrency")
	fs.IntVar(&cli.Depth, "D", 0, "max recursion depth")
	fs.IntVar(&cli.Depth, "depth", 0, "max recursion depth")
	fs.BoolVar(&cli.RecursionSmart, "rs", true, "smart recursion")
	fs.BoolVar(&cli.RecursionSmart, "recursionSmart", true, "smart recursion")
	fs.StringVar(&cli.RecursionStatusCode, "rsc", "200,301-302,403", "recursion status codes")
	fs.StringVar(&cli.RecursionStatusCode, "recursionStatusCodes", "200,301-302,403", "recursion status codes")
	fs.BoolVar(&cli.Redirect, "r", false, "follow redirects")
	fs.BoolVar(&cli.Redirect, "redirect", false, "follow redirects")
	fs.StringVar(&cli.Output, "o", "output", "output base name")
	fs.StringVar(&cli.Output, "output", "output", "output base name")
	fs.StringVar(&cli.OutputFormat, "of", "txt", "output format txt/json/html")
	fs.StringVar(&cli.OutputFormat, "outputFormat", "txt", "output format")
	fs.IntVar(&cli.ThrottleRate, "tr", 0, "requests per second")
	fs.IntVar(&cli.ThrottleRate, "throttleRate", 0, "requests per second")
	fs.IntVar(&cli.ThrottleRate, "rate", 0, "requests per second")
	fs.StringVar(&cli.Delay, "p", "", "request delay (seconds or min-max)")
	fs.StringVar(&cli.FilterStatusCode, "fsc", "", "include status codes")
	fs.StringVar(&cli.FilterStatusCode, "filterStatusCode", "", "include status codes")
	fs.StringVar(&cli.FilterStatusCodeNot, "fscn", "", "exclude status codes")
	fs.StringVar(&cli.FilterStatusCodeNot, "filterStatusCodeNot", "", "exclude status codes")
	fs.StringVar(&cli.FilterLength, "fl", "", "include lengths")
	fs.StringVar(&cli.FilterLength, "filterLength", "", "include lengths")
	fs.StringVar(&cli.FilterLengthNot, "fln", "", "exclude lengths")
	fs.StringVar(&cli.FilterLengthNot, "filterLengthNot", "", "exclude lengths")
	fs.StringVar(&cli.FilterLength, "ms", "", "match size")
	fs.StringVar(&cli.FilterLengthNot, "fs", "", "filter size")
	fs.StringVar(&cli.FilterWords, "mw", "", "match words")
	fs.StringVar(&cli.FilterWordsNot, "fw", "", "filter words")
	fs.StringVar(&cli.FilterLines, "ml", "", "match lines")
	fs.StringVar(&cli.FilterLinesNot, "fls", "", "filter lines")
	fs.StringVar(&cli.FilterTime, "mt", "", "match time in ms")
	fs.StringVar(&cli.FilterTimeNot, "ft", "", "filter time in ms")
	fs.StringVar(&cli.FilterWords, "filterWords", "", "match words")
	fs.StringVar(&cli.FilterWordsNot, "filterWordsNot", "", "filter words")
	fs.StringVar(&cli.FilterLines, "filterLines", "", "match lines")
	fs.StringVar(&cli.FilterLinesNot, "filterLinesNot", "", "filter lines")
	fs.StringVar(&cli.FilterTime, "filterTime", "", "match time in ms")
	fs.StringVar(&cli.FilterTimeNot, "filterTimeNot", "", "filter time in ms")
	fs.BoolVar(&cli.NearDuplicates, "nd", false, "near-duplicate filter")
	fs.IntVar(&cli.NearDuplicateLenBucket, "nd-len", 20, "near-duplicate length bucket")
	fs.IntVar(&cli.NearDuplicateWordBucket, "nd-words", 5, "near-duplicate word bucket")
	fs.IntVar(&cli.NearDuplicateLineBucket, "nd-lines", 5, "near-duplicate line bucket")
	fs.StringVar(&cli.BlockWords, "bw", "", "block words (csv or file)")
	fs.StringVar(&cli.InterestingStrings, "is", "", "interesting strings (csv or file)")
	fs.StringVar(&cli.FilterMatchWord, "fm", "", "contains word")
	fs.StringVar(&cli.FilterMatchWord, "filterMatchWord", "", "contains word")
	fs.StringVar(&cli.FilterMatchRegex, "mr", "", "regex include")
	fs.StringVar(&cli.FilterMatchRegex, "filterMatchRegex", "", "regex include")
	fs.StringVar(&cli.FilterStatusCode, "mc", "", "match status codes")
	fs.StringVar(&cli.FilterStatusCodeNot, "fc", "", "filter status codes")
	fs.StringVar(&cli.FilterMatchRegexNot, "mrn", "", "regex exclude")
	fs.StringVar(&cli.FilterMatchRegexNot, "filterMatchRegexNot", "", "regex exclude")
	fs.StringVar(&cli.FilterMatchRegexNot, "fr", "", "filter regex")
	fs.BoolVar(&cli.FilterRegexTextOnly, "mrt", false, "regex on text-only")
	fs.BoolVar(&cli.FilterRegexTextOnly, "filterMatchRegexTextOnly", false, "regex on text-only")
	fs.StringVar(&cli.FilterContentType, "f", "", "filter content type")
	fs.StringVar(&cli.FilterContentType, "filterContentType", "", "filter content type")
	fs.BoolVar(&cli.FilterDuplicates, "fd", false, "dedupe")
	fs.BoolVar(&cli.FilterDuplicates, "filterDuplicates", false, "dedupe")
	fs.IntVar(&cli.DuplicateThreshold, "dt", 10, "dedupe threshold")
	fs.IntVar(&cli.DuplicateThreshold, "duplicateThreshold", 10, "dedupe threshold")
	fs.BoolVar(&cli.ShowStatus, "s", false, "show all status")
	fs.BoolVar(&cli.ShowStatus, "showStatus", false, "show all status")
	fs.BoolVar(&cli.OnlyDomains, "od", false, "only domains")
	fs.BoolVar(&cli.OnlyDomains, "onlydomains", false, "only domains")
	fs.BoolVar(&cli.CheckBackslash, "cb", false, "disable trailing slash normalization")
	fs.BoolVar(&cli.CheckBackslash, "check-slash", false, "disable trailing slash normalization")
	fs.BoolVar(&cli.Bypass, "b", false, "legacy bypass mode")
	fs.BoolVar(&cli.Bypass, "bypass", false, "legacy bypass mode")
	fs.BoolVar(&cli.BypassTooManyRequests, "btr", false, "retry on 429")
	fs.BoolVar(&cli.BypassTooManyRequests, "bypassTooManyRequests", false, "retry on 429")
	fs.BoolVar(&cli.FilterTestLength, "t", false, "filter by test length")
	fs.BoolVar(&cli.FilterTestLength, "filterTestLength", false, "filter by test length")
	fs.BoolVar(&cli.FilterWrongStatus200, "fws", false, "filter wrong status 200")
	fs.BoolVar(&cli.FilterWrongStatus200, "filterWrongStatus200", false, "filter wrong status 200")
	fs.BoolVar(&cli.FilterWrongSubdomain, "fwd", false, "filter wrong subdomain")
	fs.BoolVar(&cli.FilterWrongSubdomain, "filterWrongSubdomain", false, "filter wrong subdomain")
	fs.BoolVar(&cli.FilterPossible404, "p404", false, "filter possible 404")
	fs.BoolVar(&cli.FilterPossible404, "filterPossible404", false, "filter possible 404")
	fs.BoolVar(&cli.AutoCalibrate, "ac", false, "auto calibration")
	fs.IntVar(&cli.AutoCalibrateN, "acn", 2, "auto calibration requests")
	fs.StringVar(&cli.Headers, "rah", "", "header1:val1,header2:val2")
	fs.StringVar(&cli.Headers, "requestAddHeader", "", "headers")
	fs.StringVar(&cli.Headers, "H", "", "header")
	fs.StringVar(&cli.Cookies, "C", "", "cookie1=v1,cookie2=v2")
	fs.StringVar(&cli.Cookies, "cookie", "", "cookies")
	fs.StringVar(&cli.UserAgent, "raa", "", "user agent")
	fs.StringVar(&cli.UserAgent, "requestAddAgent", "", "user agent")
	fs.BoolVar(&cli.RandomUserAgent, "random-ua", false, "randomize user agent")
	fs.StringVar(&cli.RandomizeWordlistCase, "wordlist-case", "", "wordlist case: lower|upper")
	fs.StringVar(&cli.Method, "X", "", "http method")
	fs.StringVar(&cli.Method, "method", "", "http method")
	fs.StringVar(&cli.Data, "data", "", "http data/body")
	fs.StringVar(&cli.Proxy, "x", "", "proxy")
	fs.StringVar(&cli.Proxy, "proxy", "", "proxy")
	fs.StringVar(&cli.RequestFile, "request", "", "raw request file")
	fs.StringVar(&cli.ReplayProxy, "replay-proxy", "", "replay proxy")
	fs.BoolVar(&cli.ReplayOnMatch, "replay-on-match", true, "replay only matches")
	fs.StringVar(&cli.RequestProto, "request-proto", "", "request proto")
	fs.StringVar(&cli.ProxyUser, "proxy-user", "", "proxy user")
	fs.StringVar(&cli.ProxyPass, "proxy-pass", "", "proxy pass")
	fs.StringVar(&cli.ResumeFile, "resume", "", "resume file")
	fs.IntVar(&cli.ResumeEvery, "resume-every", 0, "resume write interval (requests)")
	fs.StringVar(&cli.Verbs, "verbs", "", "http verbs csv")
	fs.BoolVar(&cli.AutoVerbs, "auto-verb", false, "auto verbs")
	fs.StringVar(&cli.StopOnStatus, "sf", "", "stop on status codes")
	fs.BoolVar(&cli.StopOnErrors, "se", false, "stop on errors")
	fs.IntVar(&cli.StopOnMatches, "sa", 0, "stop after matches")
	fs.IntVar(&cli.BypassBudget, "bypass-budget", 3, "max bypass variants per URL")
	fs.Float64Var(&cli.BypassRatioLimit, "bypass-ratio", 0.4, "max ratio of bypass requests")
	fs.BoolVar(&cli.WAFAdaptive, "waf-adaptive", false, "adaptive WAF slowdown")
	fs.IntVar(&cli.WAFSlowdownThreshold, "waf-threshold", 50, "WAF threshold (responses)")
	fs.Float64Var(&cli.WAFSlowdownFactor, "waf-factor", 2.0, "WAF slowdown factor")
	fs.BoolVar(&cli.JitterProfile, "jitter", false, "adaptive jitter profiling")
	fs.IntVar(&cli.JitterThresholdMS, "jitter-threshold", 800, "jitter threshold ms")
	fs.Float64Var(&cli.JitterFactor, "jitter-factor", 1.0, "jitter factor")
	fs.StringVar(&cli.BasicAuthUser, "bau", "", "basic auth user")
	fs.StringVar(&cli.BasicAuthUser, "basicAuthUser", "", "basic auth user")
	fs.StringVar(&cli.BasicAuthPass, "bap", "", "basic auth pass")
	fs.StringVar(&cli.BasicAuthPass, "basicAuthPass", "", "basic auth pass")
	fs.BoolVar(&cli.SafeMode, "safe", true, "safe mode on/off")
	fs.StringVar(&cli.AllowedHosts, "allow-hosts", "", "comma-separated scope hosts")
	fs.StringVar(&cli.ExcludePaths, "exclude-paths", "", "exclude path segments (csv or file)")
	fs.BoolVar(&cli.Quiet, "q", false, "quiet mode")
	fs.BoolVar(&cli.Quiet, "quiet", false, "quiet mode")
	fs.BoolVar(&cli.DumpResponses, "dump", false, "dump response bodies")
	fs.StringVar(&cli.DumpDir, "dump-dir", "", "dump response directory")
	fs.IntVar(&cli.RetryCount, "retry", 2, "retries")
	fs.IntVar(&cli.RetryBackoffMS, "retry-backoff-ms", 500, "base backoff ms")
	fs.StringVar(&cli.ConfigFilePath, "cf", "", "config file path")
	fs.StringVar(&cli.ConfigFilePath, "configfile", "", "config file path")
	fs.StringVar(&cli.Preset, "preset", "", "preset: quick (fast smoke), stealth (low profile), thorough (full discovery)")
	fs.IntVar(&cli.TimeoutSeconds, "timeout", 30, "request timeout seconds")
	fs.BoolVar(&cli.GeneratePayload, "g", false, "generate payload")
	fs.BoolVar(&cli.GeneratePayload, "generate_payload", false, "generate payload")
	fs.IntVar(&cli.GeneratePayloadLength, "gpl", 20000, "generate payload length")
	fs.IntVar(&cli.GeneratePayloadLength, "generate_payload_length", 20000, "generate payload length")
	fs.StringVar(&cli.Modules, "modules", "", "comma-separated response-analysis modules (e.g. fingerprint,cors,ai)")
	fs.StringVar(&cli.AIPrompt, "ai-prompt", "", "custom prompt for AI module; placeholders: {{status}}, {{method}}, {{url}}, {{body}}")
	fs.StringVar(&cli.AIProvider, "ai-provider", "openai", "AI module backend: openai | ollama | gemini (needs OPENAI_API_KEY, or GEMINI_API_KEY, or no key for Ollama)")
	fs.StringVar(&cli.AIEndpoint, "ai-endpoint", "", "AI module: override API URL (e.g. http://localhost:11434 for Ollama)")
	fs.StringVar(&cli.AIModel, "ai-model", "", "AI module: model name (default per provider: gpt-4o-mini, llama3.1, gemini-1.5-flash)")
	fs.IntVar(&cli.AIMaxTokens, "ai-max-tokens", 0, "AI module: max tokens in response (0 = default 150)")
	fs.IntVar(&cli.MaxTime, "maxtime", 0, "max scan duration in seconds (0=disabled)")
	fs.IntVar(&cli.MaxTimeJob, "maxtime-job", 0, "max duration per task in seconds (0=disabled)")
	fs.StringVar(&cli.RecursionStrategy, "recursion-strategy", "default", "recursion strategy: default (by status) or greedy (all matches)")
	fs.BoolVar(&cli.UseHTTP2, "http2", false, "use HTTP/2")
	fs.BoolVar(&cli.VHostFuzz, "vhost", false, "fuzz Host header (first wordlist value as Host)")
	fs.StringVar(&cli.AuditLogPath, "audit-log", "", "log every request and response to file (NDJSON); path to output file")
	fs.IntVar(&cli.AuditMaxBodySize, "audit-max-body", 0, "max request/response body size to store in audit log (0 = no limit)")
	fs.StringVar(&cli.EnqueueModuleUrls, "enqueue-module-urls", "", "comma-separated module names whose \"urls\" output is queued for scanning (e.g. urlextract,links)")
	fs.StringVar(&cli.ExtractedURLsFile, "extracted-urls-file", "", "write all extracted URLs (from urlextract/links etc.) to this file, one per line (no enqueue)")
	fs.BoolVar(&cli.InsecureSkipVerify, "insecure", false, "skip TLS certificate verification (e.g. self-signed, Burp MITM)")
	fs.BoolVar(&cli.InsecureSkipVerify, "k", false, "skip TLS certificate verification (curl-style alias)")
	fs.StringVar(&cli.LoginURL, "login-url", "", "perform login once at this URL; session cookies used for all fuzz requests")
	fs.StringVar(&cli.LoginMethod, "login-method", "POST", "HTTP method for login (GET or POST)")
	fs.StringVar(&cli.LoginUser, "login-user", "", "username for login form (field name 'username' or use login-body)")
	fs.StringVar(&cli.LoginPass, "login-pass", "", "password for login form (field name 'password')")
	fs.StringVar(&cli.LoginBody, "login-body", "", "raw request body for login (overrides login-user/login-pass)")
	fs.StringVar(&cli.LoginContentType, "login-content-type", "application/x-www-form-urlencoded", "Content-Type for login request")
	fs.StringVar(&cli.Encoders, "enc", "", "encoders: KEYWORD:enc1,enc2 (e.g. FUZZ:urlencode); multiple -enc allowed")
	fs.BoolVar(&cli.ExploreAI, "explore-ai", false, "probe base URL with fingerprint+headers, ask AI for wordlist recommendation (provider: openai | ollama | gemini, see -explore-ai-provider); then run scan")
	fs.StringVar(&cli.ExploreAIWordlistsDir, "explore-ai-wordlists-dir", "", "with -explore-ai: dir containing wordlists (e.g. wordpress.txt); if recommended file exists, run scan with it")
	fs.StringVar(&cli.ExploreAIWordlistMap, "explore-ai-wordlist", "", "with -explore-ai: name:path_or_url (e.g. wordpress:./wp.txt,typo3:https://...); multiple entries comma-separated; overrides dir lookup")
	fs.StringVar(&cli.ExploreAIProfile, "explore-ai-profile", "balanced", "with -explore-ai: quick (small/fast wordlist) | balanced | thorough (larger wordlist, more extensions)")
	fs.BoolVar(&cli.ExploreAINoCache, "explore-ai-no-cache", false, "with -explore-ai: do not use cache; always call API (default: use cache, 1h TTL)")
	fs.StringVar(&cli.ExploreAIProvider, "explore-ai-provider", "openai", "with -explore-ai: openai | ollama | gemini")
	fs.StringVar(&cli.ExploreAIEndpoint, "explore-ai-endpoint", "", "with -explore-ai: override API URL (e.g. http://localhost:11434 for Ollama)")
	fs.StringVar(&cli.ExploreAIModel, "explore-ai-model", "", "with -explore-ai: model name (default: gpt-4o-mini / llama3.1 / gemini-1.5-flash per provider)")
	fs.IntVar(&cli.ExploreAIMaxTokens, "explore-ai-max-tokens", 0, "with -explore-ai: max tokens in response (0 = default 500)")
}
